---
title: "airquality"
output: html_document
---

This application is based on airquality database, which contains daily air quality measurements in New York from May to September 1973. The data were obtained from the New York State Department of Conservation (ozone data) and the National Weather Service (meteorological data). Dataset is built in R. Source code is available on GitHub.

You can choose month and factor types using control panel located on the left side.
To show a plot, you need to click "Submit" button.
A Columnchar plot will be displayed. It will present amount of choosen factors in particular days of month.

Four different factors can be observed:
1) Ozone (ppb) :  Mean ozone in parts per billion from 1300 to 1500 hours at Roosevelt Island
2) Solar Radiation (lang) : Solar radiation in Langleys in the frequency band 4000–7700 Angstroms from 0800 to 1200 hours at Central Park
3) Wind (mph) : Average wind speed in miles per hour at 0700 and 1000 hours at LaGuardia Airport
4) Temperature (degrees F) : Maximum daily temperature in degrees Fahrenheit at La Guardia Airport.

